IgdAssignmentDxe: Fix release build failure
Since tianocore/edk2@ae83c6b7fd83 ("MdePkg: Fix null macros for XCODE5
and CLANG"), DEBUG macro evaluates the expression, causing the following
error

In file included from VfioIgdPkg/IgdAssignmentDxe/IgdAssignment.c:18:
VfioIgdPkg/IgdAssignmentDxe/IgdAssignment.c: In function 'SetupOpRegion':
VfioIgdPkg/IgdAssignmentDxe/IgdAssignment.c:309:21: error: implicit declaration of function 'GetPciName' [-Wimplicit-function-declaration]
  309 |       __FUNCTION__, GetPciName (PciInfo), Status));
      |                     ^~~~~~~~~~
MdePkg/Include/Library/DebugLib.h:383:35: note: in definition of macro '_DEBUG_PRINT'
  383 |         DebugPrint (PrintLevel, ##__VA_ARGS__);      \
      |                                   ^~~~~~~~~~~
MdePkg/Include/Library/DebugLib.h:445:9: note: in expansion of macro '_DEBUGLIB_DEBUG'
  445 |         _DEBUGLIB_DEBUG (Expression);       \
      |         ^~~~~~~~~~~~~~~
VfioIgdPkg/IgdAssignmentDxe/IgdAssignment.c:308:5: note: in expansion of macro 'DEBUG'
  308 |     DEBUG ((DEBUG_ERROR, "%a: %a: failed to allocate OpRegion: %r\n",
      |     ^~~~~

Fix it by removing the `#if !defined(MDEPKG_NDEBUG)` as the upstream
change suggests.

Signed-off-by: Tomita Moeko <tomitamoeko@gmail.com>